#!/bin/sh
bat="$(cat /sys/class/power_supply/BAT?/capacity)"
	status="$(cat /sys/class/power_supply/BAT?/status)"
	if [ "$status" = "Charging" ]; then
		ico=""
	else
		if [ "$bat" -lt 15 ]; then
			ico=" "
		elif [ "$bat" -lt 30 ]; then
			ico=" "
		elif [ "$bat" -lt 45 ]; then
			ico=" "
		elif [ "$bat" -lt 60 ]; then
			ico=" "
		elif [ "$bat" -lt 75 ]; then
			ico=" "
		elif [ "$bat" -lt 90 ]; then
			ico=" "
		elif [ "$bat" -le 100 ]; then
			ico=" "
		fi
	fi
	echo " $ico $bat% "
