#!/bin/sh
vol=$(amixer get Master | awk -F'[]%[]' '/%/ {if ($7 == "off") { print "MM" } else { print $2 }}' | head -n 1)
bars=`expr $vol / 10`
case $bars in
  0)  bar='[----------]' ;;
  1)  bar='[#---------]' ;;
  2)  bar='[##--------]' ;;
  3)  bar='[###-------]' ;;
  4)  bar='[####------]' ;;
  5)  bar='[#####-----]' ;;
  6)  bar='[######----]' ;;
  7)  bar='[#######---]' ;;
  8)  bar='[########--]' ;;
  9)  bar='[#########-]' ;;
  10) bar='[##########]' ;;
  *)  bar='[----!!----]' ;;
esac

echo -e " $vol% $bar"

exit 0
