#!/bin/sh

iwconfig wlan0 2>&1 | grep -q no\ wireless\ extensions\. && {
  echo wired
  exit 0
}

wifistate="$(cat /sys/class/net/w*/operstate)"
ethstate="$(cat /sys/class/net/e*/operstate)"

if [[ "$wifistate" = "up" ]]; then
 echo -e "直 $essid $bar |  $ethstate"
else

essid="$(iwconfig wlan0 | awk -F '"' '/ESSID/ {print $2}')"
stngth="$(iwconfig wlan0 | awk -F '=' '/Quality/ {print $2}' | cut -d '/' -f 1)"
bars="$(expr $stngth / 10)"

case $bars in
  0)  bar='[----------]' ;;
  1)  bar='[/---------]' ;;
  2)  bar='[//--------]' ;;
  3)  bar='[///-------]' ;;
  4)  bar='[////------]' ;;
  5)  bar='[/////-----]' ;;
  6)  bar='[//////----]' ;;
  7)  bar='[///////---]' ;;
  8)  bar='[////////--]' ;;
  9)  bar='[/////////-]' ;;
  10) bar='[//////////]' ;;
  *)  bar='[----!!----]' ;;
esac

 echo -e "直 $wifi |  $ethstate "
fi
exit 0
