#!/bin/sh
chosen=$(cut -d ';' -f1 ~/.local/share/emoji | wofi --show=dmenu --prompt="select emoji" | sed "s/ .*//")

[ -z "$chosen"] && exit

if [ -n "$1" ]; then
  ydotool type "$chosen"
else
  echo "$chosen" | tr -d '\n' | wl-copy
  notify-send "'$chosen' copied to clipboard." &
fi
